<?php
class Usuario {
  //-------EDITAR NOMBRE-------
  public $reemplazousuario;
  public $claveusuario;
  //------EDITAR NICK-------
  public $reemplazonick;
  public $clavenick;
  //------EDITAR CORREO-------
  public $reemplazocorreo;
  public $clavecorreo;
  //------EDITAR DIRECTION-------
  public $reemplazodirection;
  public $clavedirection;
  //------ACTIVAR USUARIO------
  public $nombreactivarusuario;
  public $claveactivarusuario;
  //-----ALTA USUARIO-------
  public $nombrealtausuario;
  public $contrasenacodaltausuario;
  public $correoaltausuario;
  public $cumpleaniosaltausuario;
  public $concatenaaltausuario;
  public $direccionaltausuario;
  //-------BAJA USUARIO---------
  public $clavebajausuario;
  //-------BLOQUEO USUARIO---
  public $clavebloqueausuario;
  //------DESBLOQUEA USUARIO----
  public $clavedesbloq;
